# Generated by Django 5.0 on 2023-12-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('pieces', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('wishlist', models.BooleanField()),
                ('built', models.BooleanField(default=False)),
                ('item_number', models.PositiveBigIntegerField()),
            ],
        ),
    ]
